### ISSUE TITLE
Added support to Chat Completion model

### ISSUE THREAD

**Issue by onlylonly** [p-e-w/arrows#4]
First, I must say the project is interesting, and thank you for open sourcing this.

I've made some changes to include support for Chat Completion model, e.g, llama-8, GPT-4. And the ability to toggle between 'chat' and 'completion' model. Not sure if this align with the project direction?

I also added some example in the config.ts

and I'll be creating a new pull request soon. 

#5

**Comment by p-e-w** [comment]
See my response in #5.
